services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: deck_of_card
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:8000
